### ISSUE TITLE
about curl command

### ISSUE THREAD

**Issue by francoiskroll** [skhaz/telegram-delduca-bot#3]
Thanks a lot for your tutorial

https://nullonerror.org/2021/01/08/hosting-telegram-bots-on-google-cloud-run/

Extremely helpful as I'm trying to find my way around.

I am getting confused at the very last step (the `curl` command). Surely I need to feed it the URL I get from gcloud deploy run, but I am not sure where.

Say for example my service URL is https://bot-r2wdu9uh2w-ew.a.run.app

How would you write the command below?

    curl "https://api.telegram.org/bot${TOKEN}/setWebhook?url=$(gcloud run services describe bot --format 'value(status.url)' --project ${PROJECT_ID})"

Thanks for your help

**Comment by skhaz** [comment]
Hi @francoiskroll, 

Thank you so much for the feedback!

If you know the URL of your service, you can hardcoded the call

```shell
curl "https://api.telegram.org/bot${TOKEN}/setWebhook?url=https://bot-r2wdu9uh2w-ew.a.run.app/"
```

Don't forget to replace the TOKEN variable!

Example

```shell
curl "https://api.telegram.org/bot1511833844:ABGWZFw3H-ddbgcu2npRr51dBpKc_jIYhTk/setWebhook?url=https://bot-r2wdu9uh2w-ew.a.run.app/"
```

You need to do this only one time.

**Comment by skhaz** [comment]
If you need more help, call me on Telegram https://t.me/skhaz
